pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo ' Buildding '
            }
        }
        stage('Test') {
            steps {
                echo 'testing'
            }
            post {
                always {
                    echo 'testing was good'
                }
            }
        }
        stage('Deliver') {
            steps {
                echo 'delivering '
            }
        }
    }
}
